-- MySQL Script generated by MySQL Workbench
-- Thu Jan 18 10:07:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `perfil_id` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_perfil_idx` (`perfil_id` ASC),
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `mydb`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orgao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orgao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `numero` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`secretaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`secretaria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_convenio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empenhado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empenhado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empenhado` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`termo-convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`termo-convenio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `termo-convenio` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`convenios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`convenios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ano` INT NOT NULL,
  `numero` INT NOT NULL,
  `orgao_id` INT NOT NULL,
  `secretaria_id` INT NOT NULL,
  `valor_global` FLOAT NOT NULL,
  `inicio` DATE NOT NULL,
  `termino` DATE NOT NULL,
  `numero_sincov` INT NOT NULL,
  `status_id` INT NOT NULL,
  `tipo_convenio_id` INT NOT NULL,
  `valor_contrapartida` FLOAT NOT NULL,
  `objeto` LONGTEXT NULL,
  `valor_repasse` FLOAT NOT NULL,
  `origem` VARCHAR(255) NOT NULL,
  `repasse` DECIMAL NOT NULL,
  `contrapartida` VARCHAR(255) NOT NULL,
  `situacao` VARCHAR(255) NULL,
  `empenhado_id` INT NOT NULL,
  `acao_id` INT NOT NULL,
  `termo-convenio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_convenios_orgao1_idx` (`orgao_id` ASC),
  INDEX `fk_convenios_secretaria1_idx` (`secretaria_id` ASC),
  INDEX `fk_convenios_status1_idx` (`status_id` ASC),
  INDEX `fk_convenios_tipo-convenio1_idx` (`tipo_convenio_id` ASC),
  INDEX `fk_convenios_empenhado1_idx` (`empenhado_id` ASC),
  INDEX `fk_convenios_acao1_idx` (`acao_id` ASC),
  INDEX `fk_convenios_termo-convenio1_idx` (`termo-convenio_id` ASC),
  CONSTRAINT `fk_convenios_orgao1`
    FOREIGN KEY (`orgao_id`)
    REFERENCES `mydb`.`orgao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_convenios_secretaria1`
    FOREIGN KEY (`secretaria_id`)
    REFERENCES `mydb`.`secretaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_convenios_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `mydb`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_convenios_tipo-convenio1`
    FOREIGN KEY (`tipo_convenio_id`)
    REFERENCES `mydb`.`tipo_convenio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_convenios_empenhado1`
    FOREIGN KEY (`empenhado_id`)
    REFERENCES `mydb`.`empenhado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_convenios_acao1`
    FOREIGN KEY (`acao_id`)
    REFERENCES `mydb`.`acao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_convenios_termo-convenio1`
    FOREIGN KEY (`termo-convenio_id`)
    REFERENCES `mydb`.`termo-convenio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
